name: App Update Check

on:
  schedule:
    - cron: '0 12 * * *'  # optional: daily at 12:00 UTC
  workflow_dispatch:
    inputs:
      message:
        description: The commit message to use
        required: false

permissions:
  contents: write

jobs:
  check:
    if: github.repository == 'boomboompower/tecg' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          always-auth: false
          node-version: 16.x
          cache: npm

      - name: Git Credentials
        shell: bash
        run: |
          git config --global user.name 'github-bot'
          git config --global user.email '6031226+github-bot@users.noreply.github.com'

      - run: npm install
      - run: npm run build --if-present
        env:
          EXPERIMENTS_URL: ${{ secrets.EXPERIMENTS_URL }}
          EXPERIMENTS_DATA_URL: ${{ secrets.EXPERIMENTS_DATA_URL }}
          # If a workflow dispatch, and the message is 'force', then force update
          FORCE_UPDATE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.message == 'force' && 'true' || 'false' }}

      - run: npm run build-step-2 --if-present
      - run: npm run build-step-3-extended --if-present
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: 'boomboompower'
          GH_REPO: 'tecg'

      - name: Done
        run: |
          echo Goodbye!
